dist: trusty
language: php
php:
  - "7.3"
addons:
  sonarcloud:
    organization: "f-s-c"
    token: $SONAR_TOKEN
services:
  - mysql
before_script:
  - cd src
  - mysql -e 'CREATE DATABASE fsc_emotionally;'
  - mysql -e "CREATE USER 'fsc'@'localhost' IDENTIFIED WITH mysql_native_password;"
  - mysql -e "GRANT ALL PRIVILEGES ON fsc_emotionally.* TO 'fsc'@'localhost';"
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - php artisan serve &
script:
  # - php artisan dusk
  - cd ..
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
