<?php
/**
 * This file is part of Emotionally.
 *
 * Emotionally is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Emotionally is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Emotionally.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace Emotionally\Http\Controllers\ReportFormatters;

use PhpOffice\PhpPresentation\DocumentLayout;
use PhpOffice\PhpPresentation\IOFactory;
use PhpOffice\PhpPresentation\PhpPresentation;
use PhpOffice\PhpPresentation\Slide;
use PhpOffice\PhpPresentation\Slide\Background\Color as BackgroundColor;
use PhpOffice\PhpPresentation\Style\Alignment;
use PhpOffice\PhpPresentation\Style\Color;

abstract class ReportPptxPresentation
{
    /**
     * The type of report
     */
    protected const TYPE = 'NO TYPE';

    /**
     * @var PhpPresentation The presentation
     */
    protected $presentation;
    protected $title;

    /**
     * @var array The report of the presentation
     */
    protected $report;

    /**
     * @var Slide The title slide.
     */
    protected $title_slide;

    /**
     * ReportPptxPresentation constructor.
     * @param string $title The title of the presentation.
     * @param array|string $report The report to be presented.
     */
    public function __construct(string $title, $report)
    {
        $this->title = trim($title);

        if (is_string($report)) {
            $report = json_decode($report, true);
        } elseif (!is_array($report)) {
            throw new \InvalidArgumentException('$report must be a string or an array');
        }
        $this->report = $report;

        $this->presentation = new PhpPresentation();

        $this->presentation->getDocumentProperties()
            ->setCreator(\Auth::user()->name . ' ' . \Auth::user()->surname)
            ->setLastModifiedBy('Emotionally - FSC');

        $this->presentation->getLayout()
            ->setDocumentLayout(DocumentLayout::LAYOUT_SCREEN_16X9);

        $this->createTitleSlide();
    }

    /**
     * Create the title slide.
     */
    private function createTitleSlide()
    {
        $this->title_slide = $this->presentation->getActiveSlide();
        $background = (new BackgroundColor())->setColor(new Color('FFFF9800'));
        $this->title_slide->setBackground($background);

        $shape = $this->title_slide->createRichTextShape()
            ->setHeight(300)
            ->setWidth(600)
            ->setOffsetX(180)
            ->setOffsetY(120);
        $shape->getActiveParagraph()->getAlignment()
            ->setHorizontal(Alignment::HORIZONTAL_CENTER)
            ->setVertical(Alignment::VERTICAL_CENTER);
        $textRun = $shape->createTextRun($this::TYPE);
        $textRun->getFont()->setBold(true)
            ->setSize(32)
            ->setCharacterSpacing(10)
            ->setColor(new Color('FFFFFFFF'));
        $shape->createBreak();
        $textRun = $shape->createTextRun($this->title);
        $textRun->getFont()->setBold(true)
            ->setSize(60)
            ->setColor(new Color('FFFFFFFF'));
        $shape->createBreak();
        $textRun = $shape->createTextRun('Generated by Emotionally, made with love by FSC');
        $textRun->getFont()
            ->setSize(11)
            ->setColor(new Color('DDFFFFFF'));
    }

    /**
     * @return Slide Get a reference to the title slide.
     */
    public function getTitleSlide()
    {
        return $this->title_slide;
    }

    /**
     * Get the output file name.
     * @return string The file name. It consist of an ISO timestamp, the presentation title and an extension.
     * @throws \Exception Emits Exception in case of an error.
     */
    public function getFileName()
    {
        $date = new \DateTime();
        $base_iso_date_format = 'Ymd\THis';
        return $date->format($base_iso_date_format) . ' - ' . $this->title . '.pptx';
    }

    /**
     * Download the presentation as a Power Point 2007 file (.pptx).
     * @throws \Exception
     */
    public function downloadPresentation()
    {
        $writer = IOFactory::createWriter($this->presentation, 'PowerPoint2007');
        $writer->save('php://output');
    }
}
