<?php

namespace Emotionally\Http\Controllers;

use http\Exception\InvalidArgumentException;
use Illuminate\Http\Request;
use PhpOffice\PhpPresentation\DocumentLayout;
use PhpOffice\PhpPresentation\IOFactory;
use PhpOffice\PhpPresentation\PhpPresentation;
use PhpOffice\PhpPresentation\Slide\Background\Color as BackgroundColor;
use PhpOffice\PhpPresentation\Style\Alignment;
use PhpOffice\PhpPresentation\Style\Color;

class ReportPptxPresentation
{
    private $presentation;
    private $title;

    /**
     * @var array The report of the presentation
     */
    private $report;

    private $title_slide;

    /**
     * ReportPptxPresentation constructor.
     * @param string $title The title of the presentation.
     * @param array|string $report The report to be presented.
     */
    public function __construct(string $title, $report)
    {
        $this->title = $title;

        if(is_string($report)){
            $report = json_decode($report, true);
        }elseif (!is_array($report)){
            throw new \InvalidArgumentException('$report must be a string or an array');
        }
        $this->report = $report;

        $this->presentation = new PhpPresentation();

        $this->presentation->getDocumentProperties()
            ->setCreator(\Auth::user()->name . ' ' . \Auth::user()->surname)
            ->setTitle('Video report - ' . $title)
            ->setLastModifiedBy('Emotionally - FSC')
            ->setSubject('Video report');
        $this->presentation->getLayout()
            ->setDocumentLayout(DocumentLayout::LAYOUT_SCREEN_16X9);

        $this->createTitleSlide();
    }

    private function createTitleSlide()
    {
        $this->title_slide = $this->presentation->getActiveSlide();
        $background = (new BackgroundColor())->setColor(new Color('FFFF9800'));
        $this->title_slide->setBackground($background);

        $shape = $this->title_slide->createRichTextShape()
            ->setHeight(300)
            ->setWidth(600)
            ->setOffsetX(180)
            ->setOffsetY(120);
        $shape->getActiveParagraph()->getAlignment()
            ->setHorizontal(Alignment::HORIZONTAL_CENTER)
            ->setVertical(Alignment::VERTICAL_CENTER);
        $textRun = $shape->createTextRun('VIDEO');
        $textRun->getFont()->setBold(true)
            ->setSize(32)
            ->setCharacterSpacing(10)
            ->setColor(new Color('FFFFFFFF'));
        $shape->createBreak();
        $textRun = $shape->createTextRun($this->title);
        $textRun->getFont()->setBold(true)
            ->setSize(60)
            ->setColor(new Color('FFFFFFFF'));
        $shape->createBreak();
        $textRun = $shape->createTextRun('Generated by Emotionally, made with love by FSC');
        $textRun->getFont()
            ->setSize(11)
            ->setColor(new Color('DDFFFFFF'));
    }

    public function getTitleSlide()
    {
        return $this->title_slide;
    }

    public function downloadPresentation(){
        $writer = IOFactory::createWriter($this->presentation, 'PowerPoint2007');
        $writer->save('php://output');
    }
}
